### ISSUE TITLE
Talas stuck inside table

### ISSUE THREAD

**Issue by IttyBittyNiko** [xavier150/MMVS#10]
![MacroMicroVRService-Win64-Shipping_Wowxamw5Vu](https://user-images.githubusercontent.com/100245642/155273760-08e65003-51c2-49f4-a02c-91855ff33b28.png)

I'm not really sure how this happened. Talas keeps doing the check under sole animation while he is stuck.

**Comment by xavier150** [comment]
@IttyBittyNiko 
Thanks for the report! 
You know how reproduce it ?

**Comment by xavier150** [comment]
Hello, Thanks for the report! Since this issue was fixed so I will close it
