### ISSUE TITLE
v0.4.3.2 - Game immediately crashes upon opening. (Fatal Error)

### ISSUE THREAD

**Issue by philkc33** [xavier150/MMVS#102]
After I open the game, black screen and message saying "fatal error". My computer exceeds the System Requirements and my drivers are updated.
![Screenshot_20221115_071424](https://user-images.githubusercontent.com/118319252/202052123-9f007303-78c9-4652-a1ae-082a82ecffd1.png)

**Comment by xavier150** [comment]
Hello, what your System Requirements?
OS:
CPU:
GPU:

Are you okay for doing test with Pre Alpha build ?
If yes you can contact me on discord?

You are not alone with this error, I will use this issue post for centralise it.

**Comment by xavier150** [comment]
Same error with Kennosuke: Game immediately crashes upon opening. (Fatal Error)

OS - Windows 10 Pro
CPU - 12700K
GPU - RTX 3080Ti FE
RAM - 32GB DDR4
Kennosuke#1776

**Comment by philkc33** [comment]
OS: Windows 11 Pro
CPU: Intel(R) Core(TM) i9-12900K
GPU: NVIDIA GeForce RTX 3080

Sure, I'm open to it. My Discord name is C_kaiser14.

**Comment by DukeHorus** [comment]
OS: Windows 10 10 Pro
CPU: Intel 12th Gen Core i7 - 12700K
GPU: 12GB MSI GeForce RTX 3080 SUPRIM X LHR GDDR6X
Discord ID: 183256678345474048

**Comment by xavier150** [comment]
Hello look like it was a bug on Intel code and RTX 3080. You all have this configuration. 

Since v0.4.3.3 it seams fixed. You can confirm me this all?

**Comment by xavier150** [comment]
Fixed, in v0.4.3.3 look like is was an engine error
