### ISSUE TITLE
Issues with Talas Getting Stuck

### ISSUE THREAD

**Issue by BarefootMapMaker** [xavier150/MMVS#11]
He got stuck on me, on the edge of the bed, upon which he was standing.  While he was there, all he would do was keep checking his soles.  I had to restart the game to correct it.

**Comment by xavier150** [comment]
Thanks for the report, I fixed this issue for the next update in april 
v0.4.1: https://github.com/xavier150/MMVS/blob/main/ReleaseLog/v0.4.1_Alpha.md
