### ISSUE TITLE
v0.4.3.4 talas ai doesn't take off the shoes (suggestion)

### ISSUE THREAD

**Issue by justfiction** [xavier150/MMVS#112]
Doesn't look like it's winter in the cozy home map, but the shoes are winter ones.
His feet must get really hot in there.
If I was him, I would take them off after a bit.

**Comment by xavier150** [comment]
Fixed for the next version
https://github.com/xavier150/MMVS/blob/main/ReleaseLog/v0.4.4_Alpha.md
I will close this issue after v0.4.4 release
