### ISSUE TITLE
Left stick not working

### ISSUE THREAD

**Issue by Xalder60** [xavier150/MMVS#14]
For some reasons the left stick of my VR controllers (quest 2 ones) isn't doing anything making me unable to walk around. Tried restarting the game but didn't work. it happens everytime. 

Next time I  can hop in I'll try using the steam VR menu to change controls

**Comment by xavier150** [comment]
Hello xalder,
Thank you for the report. That now fixed for the next version v0.4.1
Linear moving and scroll in menu use the same keys but Steam VR don't understand. That an problem with the Steam VR Keys generation.
Also I will change some keys for HTC and Oculus. Better ergonomic and more logic control.

**Comment by xavier150** [comment]
https://github.com/xavier150/MMVS/blob/main/ReleaseLog/v0.4.1_Alpha.md
