### ISSUE TITLE
Guest connections cannot use certain actions as a game master

### ISSUE THREAD

**Issue by Lightshadow368** [xavier150/MMVS#17]
![60F5CA70-1A37-4CAD-BC93-D877A8959C82](https://user-images.githubusercontent.com/100322099/155429665-f1dd8e2e-6c46-48be-9ed1-e4fc6f4c4388.jpeg)
(Borrowed screenshot from another user)
As a game master on the host machine, the options marked as “2” in the screenshot appear as normal. However, as a game master on a guest connection (non-host), this dropdown does not have any options available to the user.

**Comment by xavier150** [comment]
Hello @Lightshadow368 You still have this bugs in v0.4.0.1 ?

**Comment by xavier150** [comment]
Hello, thanks again for the report! 
Since this issue was fixed, I will close it
