### ISSUE TITLE
Talas AI Bug

### ISSUE THREAD

**Issue by Lightshadow368** [xavier150/MMVS#19]
The Talas AI stops functioning when the player is pinned in certain places. So far, the ones I have found is while pinned under him on a chair or while pinned on the table. There may be others as well, but I haven’t seen them yet.

**Comment by xavier150** [comment]
Hello, this should be fixed with the AI Fix, I will close this issue after release v0.4.3.4
https://github.com/xavier150/MMVS/edit/main/ReleaseLog/v0.4.3.4_Alpha.md
