### ISSUE TITLE
Bug - Talas standing on the couch arm

### ISSUE THREAD

**Issue by recentteen14** [xavier150/MMVS#2]
Forgot to grab a screenshot before restarting the session, but I got Talas stuck on the arm of the large couch. I had been running around near the windows, got him to come over, and got myself stuck to his foot via game master shenanigans. Apparently, Talas didn't have enough room to do his actions on the floor, because he got popped up onto the couch arm by the window and was stuck, unable to get down or do most actions.

**Comment by recentteen14** [comment]
Update - got him to do it again with the other side of the couch, he sat right next to it and got stuck. Tried using the various commands to get him down, nothing's worked so gonna restart the session, but did find a hilarious interaction where he can stomp places nowhere near him.
https://imgur.com/a/nGIxPyS since the screenshots are too big for Github and I'm too lazy to shrink them

**Comment by SparkYouTube** [comment]
This got a great laugh out of me XD

**Comment by xavier150** [comment]
Thanks for the report ^^ Yeah laugh a lot too x)

This is a cumulation of several bugs:
- When Talas sit on floor he can overlap walls and pass through objects.
- Talas has no max stomp distance.

For the sit on floor I fixed this with the hotfix v0.4.0.1 
https://github.com/xavier150/MMVS/blob/main/ReleaseLog/v0.4.0.1_Alpha.md

Now I will fix the stomp max distance and add a button for respawn Talas.

**Comment by xavier150** [comment]
Oh that fixed, I will publish the v0.4.1 in April. 
https://github.com/xavier150/MMVS/blob/main/ReleaseLog/v0.4.1_Alpha.md
