### ISSUE TITLE
Dedicated server crashes

### ISSUE THREAD

**Issue by MangoLeFroot** [xavier150/MMVS#20]
The server crashes when I try to launch it. 
I uploaded the crash report [here](https://mega.nz/file/vt8hFaZD#CXY0Lw0-foMinwoSG3yCPePjjyzG8ZTM85ju1TbdtVA)

**Comment by xavier150** [comment]
Hello @MangoLeFroot,
Thanks for the report! That now fixed for the next version v0.4.1 https://github.com/xavier150/MMVS/blob/main/ReleaseLog/v0.4.1_Alpha.md
