### ISSUE TITLE
Spelling/Grammar errors (Not a big issue)

### ISSUE THREAD

**Issue by SparkYouTube** [xavier150/MMVS#21]
"He measures 5.94 ft without horns"
Imperial doesn't use decimals in their measurements of height

Correct version:
"Talas measures 5'9" without horns"

"spoted out of view, not spoted, etc
Just need to make sure that all "spotted" is with with two Ts

"Wants to Play with Micro"
changed to
"Wants to play with micro"

And a few other things but nothing too big that its game changing

**Comment by xavier150** [comment]
Thanks for the report!
I do some change but I will not able for the moment with Imperial decimals because that engine part.
I keep this issue open.

**Comment by xavier150** [comment]
Hello! Since this issue was fixed. Thanks again for the report!
I will close this issue
