### ISSUE TITLE
0.4.0-game master-object outline

### ISSUE THREAD

**Issue by daev1d** [xavier150/MMVS#26]
![outline](https://user-images.githubusercontent.com/100413014/155705574-1d96349c-9464-48e0-88cf-14413fe2c6fd.png)
Steps to reproduce:
1) start the game on desktop mode with hmd plugged in
2) play/host
3) enter game master mode
4) press k to enter vr mode
5) press k to exit vr mode

**Comment by xavier150** [comment]
Hello! thanks for the report! you still have this issue in the last version ?

**Comment by xavier150** [comment]
Hello! Since this issue was fixed so I will close it
