### ISSUE TITLE
0.4.0-debug menu-mask doesn't update dirt factor

### ISSUE THREAD

**Issue by daev1d** [xavier150/MMVS#27]
![clean](https://user-images.githubusercontent.com/100413014/155710554-069705d6-54f9-43ec-af65-3755218db1bc.png)
When changing the mask, the dirt factor doesn't automatically update.
You can manually force the dirt factor to update by touching each sole.

**Comment by xavier150** [comment]
Thanks for the report! 
I fixed this for the next update in april.
v0.4.1 https://github.com/xavier150/MMVS/blob/main/ReleaseLog/v0.4.1_Alpha.md
