### ISSUE TITLE
0.4.0 - Doors Desync'd for Clients

### ISSUE THREAD

**Issue by Scapegoat02** [xavier150/MMVS#28]
Steps to reproduce:

1. Host a game
2. Game master and have Talas open a door
3.  Players join and doors appear closed.
4. Clients can phase through doors that are open for the host but appear closed to them
5. Invisible forces act on clients that are trying to move where a door opened should be, but it appears there's nothing there.

**Comment by xavier150** [comment]
Hey @Scapegoat02,
Thank you for the report! 
I fixed this bug with the hotfix v0.4.0.1 :3
https://github.com/xavier150/MMVS/blob/main/ReleaseLog/v0.4.1_Alpha.md
