### ISSUE TITLE
"mental" empty?

### ISSUE THREAD

**Issue by RidleyMK** [xavier150/MMVS#32]
![image](https://user-images.githubusercontent.com/48699005/155901511-f735ab94-c668-41a5-958b-881fc3260fbd.png)

**Comment by RidleyMK** [comment]
I think there's something missing between "Mental" and "Character Actions". <-<

**Comment by xavier150** [comment]
Oh yeah I removed some sliders I will add it again when AI will work as I want :3 
That for have more control on want Talas want to do.

**Comment by xavier150** [comment]
I close this issue for duplicate, You can speak about here: https://github.com/xavier150/MMVS/issues/16
