### ISSUE TITLE
Talas stays stuck in front of the coffee table

### ISSUE THREAD

**Issue by Nomaxice** [xavier150/MMVS#33]
When climbing on the coffee table (or on its shelf), Talas often gets stuck for a while uncertain of what to do, his locomotion system failing with the next order flashing on and off. Eventually moving around on the table he'll finally move onto the table if hitting just the right area.

https://user-images.githubusercontent.com/10945524/155907839-92ef7c01-b1a4-4e8c-a886-8574a15db53a.mp4

**Comment by xavier150** [comment]
Hello, Thanks for the report! Since this issue was fixed so I will close it. I have also do a lot of fix with the AI in the last versions.
https://github.com/xavier150/MMVS/edit/main/ReleaseLog/v0.4.3.4_Alpha.md
