### ISSUE TITLE
talas lift both feet

### ISSUE THREAD

**Issue by daev1d** [xavier150/MMVS#35]
![lift feet](https://user-images.githubusercontent.com/100413014/156551732-56238d5a-6c83-4acf-baad-3b7dfb43014f.png)
This is present in 0.4.0 and 0.4.0.1

**Comment by xavier150** [comment]
Hello @daev1d,
Thank you for the report! That now fixed for the next version v0.4.1

https://user-images.githubusercontent.com/7216958/158729666-1da77cd8-1701-460c-bf3c-a7b2ae31525f.mp4
