### ISSUE TITLE
GameMaster, no Talas / Character Actions menu

### ISSUE THREAD

**Issue by daev1d** [xavier150/MMVS#36]
![talas no command](https://user-images.githubusercontent.com/100413014/156553049-8245241b-4fe3-4a2d-8ce4-7b727b58ce91.png)

Steps to reproduce:
1. Become Game Master
2. Disable Talas AI
3. Command talas to do any character action
4. Switch to Micro
5. Switch back to Game Master

**Comment by ThXRay** [comment]
Not really a bug actually, but maybe a bit of an oversight. You can select Talas again by clicking the mouse icon on the top left, then clicking Talas.

**Comment by xavier150** [comment]
Hello, Thank for the report! 
Yeah that's not really a bug. All tools is deselected when you switch game master / micro, it's not very intuitive.
Now in v0.4.1 you will keep the game master state with selected tool and select target.
https://github.com/xavier150/MMVS/blob/main/ReleaseLog/v0.4.1_Alpha.md
