### ISSUE TITLE
Camera rotation resets in multiplayer

### ISSUE THREAD

**Issue by IanCorvid** [xavier150/MMVS#38]
Description: While in Multiplayer, with multiple players, If one controlling a micro steps in to a Teleporter spot, it forces the cameras of al other Micros and the Game Master to look towards that particular teleporter. 

Version: V0.4.0.1 - Alpha

**Comment by xavier150** [comment]
Hello, 
Oh my this is a very bad bug... Thanks for the report!
That now fixed for the next version v0.4.1

**Comment by xavier150** [comment]
https://github.com/xavier150/MMVS/blob/main/ReleaseLog/v0.4.1_Alpha.md
