### ISSUE TITLE
BUG: "ERROR NAME" and controls locked in VR when trying to use car under bed.

### ISSUE THREAD

**Issue by sabertooth604** [xavier150/MMVS#4]
Controls locked up when attempting to use the car located under the bed whilst in VR (Using a Valve Index).

"ERROR NAME" displayed and goes to third party front view of Cobble. (See screenshot)

![MMVS - Bug - Use car bug -in Valve Index VR-](https://user-images.githubusercontent.com/26451878/155243137-4f4c8b95-0fe2-49a3-8ff3-12590c702d84.png)

Was able to switch to desktop mode, and move the car normally, however, the controls will lock up again shortly after attempting to go back to VR mode.

NOTE: menu can be brought up and used without any issue throughout this issue.

**Comment by xavier150** [comment]
Hello! Thanks for the report!
I fixed this issue for the next update v0.4.3.1
I will close this issue after the release.
Release Log: https://github.com/xavier150/MMVS/blob/main/ReleaseLog/v0.4.3.1_Alpha.md

About VR it sill no possible to control Car in VR. I move this as an suggestion here: 
https://github.com/xavier150/MMVS/issues/86
