### ISSUE TITLE
Micro changing stuck position

### ISSUE THREAD

**Issue by Nobody-NameStolen** [xavier150/MMVS#41]
Sometimes the micro changes position when stuck on Talas's talons, normally when Talas is walking, jumping off a table or squeezing with talons. This isn't a very big issue, just maybe a small bug

In clip 1, it is slightly hard to see but the micro was stuck in the middle of the talon or right above it and when Talas jumped off the table, he was at the top of the toe.

In clip 2, The micro was in the middle of the talon and when squeezed, changed talons which is ok and a nice touch but he moved to the rear toe which was outside of the grasp and doesn't make much sense. 

Sorry for the long read, I don't have anything better to do ;)

https://youtu.be/KBtcHAFN4rw     -   clip 1
https://youtu.be/MwFXNjkUWkM    -  clip 2

**Comment by xavier150** [comment]
Hello, Thanks for the report! Since this issue was fixed so I will close it
