### ISSUE TITLE
VR Multiplayer Issues

### ISSUE THREAD

**Issue by SurgeFloof** [xavier150/MMVS#46]
Getting crushed or swallowed in multiplayer results in the player using VR to glitch out and disappear from the original spot where they were crushed or swallowed. The viewpoint is then made sideways. Also while the VR-Player is using the text chat provided in the game, every message that pops up causes a tremendous drop in FPS, causing the player to freeze for a moment.

**Comment by xavier150** [comment]
Hello! thanks for the report, since this bugs was fixed so I will close it.
