### ISSUE TITLE
32 bits support for new versions

### ISSUE THREAD

**Issue by georgewashington12** [xavier150/MMVS#48]
hello. i use 34 bits pc, and i had problem with version 0.3.1 it was crashing, but 0.3.0 was not, so is it possible to play with more advanced versions? i think not, right? and will there be any new versions with 34 bits, thanks, i really just want to play that game, please... thank you for your cooperation

**Comment by xavier150** [comment]
Hello @georgewashington12 
Unfortunately I will not able to make the game again supported for 32 bits in the next version :/
I switched to Unreal Engine 5 and it does not support 32-bit platforms, and there are no plans to add 32-bit platform support in the future.

For more info about the Recommended system requirements: [Wiki page](https://github.com/xavier150/MMVS/wiki/System-requirements)
For more info about Unreal Engine 5 migration: [UE5 doc page](https://docs.unrealengine.com/5.0/en-US/unreal-engine-5-migration-guide/)
