### ISSUE TITLE
Gameplay bug, Dedicated server, stuck mechanic, v4.1.1

### ISSUE THREAD

**Issue by DefinitelyNotARock** [xavier150/MMVS#49]
On both of the dedicated servers for the game, the mechanic in which you get stuck to Talas doesn't work. To test this I tried both the linux server and windows dedicated server, as well as modified chance to get stuck to be 1 always, and unstuck to be 0. On both servers the micro never got stuck, but when I made the same settings on the client hosted version it worked.

Edit:
Ive been informed that this is a matter of only the host can change that game setting. If possible a command line for the server or game configuration file would be appreciated.

**Comment by xavier150** [comment]
Hello! thanks for the report! This bug is fixed in the next version.
v0.4.3.2 -> https://github.com/xavier150/MMVS/edit/main/ReleaseLog/v0.4.3.2_Alpha.md
I will close this issue after the release.
