### ISSUE TITLE
Talas stuck looking at player while facing other direction (player is undetected)

### ISSUE THREAD

**Issue by IttyBittyNiko** [xavier150/MMVS#5]
This seems to happen when the player keeps getting detected and Talas keeps losing sight of player.

**Comment by xavier150** [comment]
Hello @IttyBittyNiko This happend when you respawn ?

**Comment by xavier150** [comment]
Hello, this should be fixed with the AI Fix, I will close this issue after release v0.4.3.4
https://github.com/xavier150/MMVS/edit/main/ReleaseLog/v0.4.3.4_Alpha.md
