### ISSUE TITLE
VR Mode 0.4.1.1 Camera View becomes offset

### ISSUE THREAD

**Issue by DarkArtzDragon** [xavier150/MMVS#59]
Noticed with a few VR users in 0.4.1.1. When in a hosted server as a client, when Talas drops to floor or let's fall, the default view of the camera of the player becomes angled or angled. This has been talked by a few VR players. Until one uses a teleport point or respawn, that the camera returns to normal default. I will try and take video.

**Comment by xavier150** [comment]
Hello, Thanks for the report!
You was able to take a video? You still have this issue in the last versions of the game?

**Comment by xavier150** [comment]
Since this issue was fixed with the teleporters. I will close it
