### ISSUE TITLE
0.4.2 Lumen Room Graphical Light Issues

### ISSUE THREAD

**Issue by DarkArtzDragon** [xavier150/MMVS#64]
Hello,
I've had visual/graphical glitches appear when playing in the Lumen testing room. Pictures below:
![PXL_20221008_050902123](https://user-images.githubusercontent.com/107382124/194806300-0f12ef99-7e9a-496d-9391-ee75c5c73efb.jpg)
![PXL_20221008_050939833](https://user-images.githubusercontent.com/107382124/194806308-70131f85-cd85-474c-883a-58153aa5ef57.jpg)
![PXL_20221008_051042829](https://user-images.githubusercontent.com/107382124/194806314-58419d24-5e79-4bd1-b850-d0e5b168fbed.jpg)
![PXL_20221008_051047104](https://user-images.githubusercontent.com/107382124/194806315-072d9c45-6b1d-4db6-84ea-a3639ce97fe6.jpg)
I haven't been able to reproduce these. This happened before correcting the saved files for 0.4.1 and 0.4.2.
After correcting the saved files, I haven't been able to reproduce.

There is another issue though. When looking around in the area in a stationary spot, the lights turn to complete darkness if you look at dark area not lit up my lighting. Both standard or lumen lighting mode.

**Comment by xavier150** [comment]
![image](https://user-images.githubusercontent.com/7216958/213872809-881b8016-db4a-4fa3-a7bb-74a268dce6e4.png)
This same because the outlight effet.
