### ISSUE TITLE
v0.4.3 - Boots freeze in place when player is inside 

### ISSUE THREAD

**Issue by LtLukin** [xavier150/MMVS#76]
There is also a bug where when Talas put on boots with Cobble inside and then walk, the boots do not move with him. They just stay in one place and play the animations of walking. When he put on boots without Cobble inside, it works just fine.

Below is a link to google drive with video demonstrations of the bug:
https://drive.google.com/file/d/1t8NcL8jyPlHqEYwKlbVb91uw8rv8soAj/view?usp=sharing

**Comment by xavier150** [comment]
Thanks for the report! I will add the other comments:

------------

'I was able to recreate that particular bug consistently as shown in the video (sorry for the quality, I had to get it under 8MB). My basic goal was to get the micro inside the shoe and for Talas to wander around on his own while trampling him continuously. Here are the steps:

While in GM mode and with Talas' Free Mode OFF, I set Talas to put his shoes on.
I quickly put Talas back in Free Mode AFTER his "putting shoes on" animation starts with the idea that he will continue to walk around on his own with the micro still in the shoe (if you put him in Free Mode before the animation starts, he will immediately wander away).
Already positioned directly in front of the shoe, I quick-menu to become a micro and press "E" on one of the prompts in the shoe to teleport the micro into position before Talas' foot enters.
After a couple steps, the micro clips outside of the shoe (onto one of the shoe's exterior sticking points, I assume). Meanwhile, the shoes remain constrained to Talas' motion (i.e. animation), but become desynchronized from his actual geometry.

I hope this helps!"

[Video]

------------

"-The A to B movement seems to bug out being able to to back to the pause menu for some reason. Its pretty hard to get the pathfinding lines to go away once a path has been marked.
-When Talas puts on shoes with a tiny in them (not pushing e), they moonwalk 😂"

![Shoe moonwalk](https://user-images.githubusercontent.com/7216958/199653846-e8435e1c-053d-4cc1-bdd1-cafcbfc3eff2.gif)
