### ISSUE TITLE
v0.4.3 - Text formatting is when choosing a scenario

### ISSUE THREAD

**Issue by LtLukin** [xavier150/MMVS#79]
When you choose a scenario, you can see a debug? code under the description of scenarios. 
It says: _{CharacterType} scale: {CharacterScale} ({CharacterSize})_

Below is a screenshot where you can see this debug code:
![Debug code](https://user-images.githubusercontent.com/117294361/199541727-3ec30947-29f9-4d7b-855c-7dd8ba6ac9ff.png)

**Comment by xavier150** [comment]
Thanks for the report!
I fixed this issue for the next update v0.4.3.1
I will close this issue after the release.
Release Log: https://github.com/xavier150/MMVS/blob/main/ReleaseLog/v0.4.3.1_Alpha.md
