### ISSUE TITLE
Missing Textures on Ground Debris(?)

### ISSUE THREAD

**Issue by pah2974** [xavier150/MMVS#9]
There's these little bits of what I'm assuming is supposed to be dust or general dirt scattered around (under the glass table in the main room, inside the respawn room, and in the first vent to name a few spots), and they're all using a grey checkerboard texture. I attached a couple images below.

![MacroMicroVRService-Win64-Shipping_H30aENvtC8](https://user-images.githubusercontent.com/54547324/155266604-564a3fe4-2edc-48bd-a234-c5fcf65193a7.png)
![MacroMicroVRService-Win64-Shipping_wHkPsZldXL](https://user-images.githubusercontent.com/54547324/155266607-b6b5920f-9811-465e-8540-984464cda145.jpg)
.

**Comment by xavier150** [comment]
Hey pah2974, Thanks for the report! 
That now fixed for the next version v0.4.1 
![image](https://user-images.githubusercontent.com/7216958/159397592-0fc7326f-a530-425d-8760-8818dda0712f.png)

**Comment by xavier150** [comment]
https://github.com/xavier150/MMVS/blob/main/ReleaseLog/v0.4.1_Alpha.md
