### ISSUE TITLE
v0.4.3.1 Switching from VR mode back to Desktop Mode

### ISSUE THREAD

**Issue by TheBestNightSky** [xavier150/MMVS#97]
When switching from VR mode back to Desktop mode UI elements such as the pause menu remain in VR mode.
Hitting escape after switching from VR mode seems like it unfocused the window at first but if you hit K again you will see the pause menu is open in VR mode.

**Comment by xavier150** [comment]
Redirect -> https://github.com/xavier150/MMVS/issues/92
